name: example
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2 
  extended_tabs:
    path: ../    
  ff_annotation_route_library: ^3.0.0
  flutter:
    sdk: flutter    
  url_launcher: 6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
